name: Actions for Gradebook Project
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    Gradebook-API-Actions:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: Create .env file
              shell: bash
              env:
                  NODE_ENV: ${{ secrets.NODE_ENV }}
                  PORT: ${{ secrets.PORT }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DB_NAME: ${{ secrets.DB_NAME }}

              run: |
                  touch .env
                  echo NODE_ENV="$NODE_ENV" >> .env
                  echo PORT="$PORT" >> .env
                  echo DB_HOST="$DB_HOST" >> .env
                  echo DB_USERNAME="$DB_USERNAME" >> .env
                  echo DB_PASSWORD="$DB_PASSWORD" >> .env
                  echo DB_PORT="$DB_PORT" >> .env
                  echo DB_NAME="$DB_NAME" >> .env

            - run: npm ci
            - run: pm2 startOrRestart ecosystem.config.js --env production
